### PR TITLE
Fix crash when no displays are detected

### LINKED ISSUE #258: SMM Crash on first launch: panic: runtime error: index out of range [0] with length 0
I just downloaded the AppImage from your website and tried launching it for the first time. It looks like it correctly identified the installation location of satisfactory and then crashes:

```
[msrd0g@msrd0-tower ~]$ ./SatisfactoryModManager_linux_amd64.AppImage
2024-10-22T15:20:32+02:00 INF SatisfactoryModManager/main.go:55 starting Satisfactory Mod Manager version=3.0.3 commit=eab4298f6fdfd6b14c10d158a34cd3b7807783de date=2024-10-21T18:40:33Z type=appimage
2024-10-22T15:20:32+02:00 INF cli/profiles.go:177 saving profiles path=/home/msrd0g/.local/share/ficsit/profiles.json
2024-10-22T15:20:32+02:00 INF cli/installations.go:102 saving installations path=/home/msrd0g/.local/share/ficsit/installations.json
2024-10-22T15:20:33+02:00 INF ficsitcli/metadata.go:27 failed to find installations error="Legendary not installed"
2024-10-22T15:20:33+02:00 INF ficsitcli/metadata.go:27 failed to find installations error="Heroic not installed"
2024-10-22T15:20:33+02:00 INF ficsitcli/metadata.go:27 failed to find installations error="failed to get snap path: failed to read heroic snap dir: open /home/msrd0g/snap/heroic: no such file or directory"
2024-10-22T15:20:33+02:00 INF ficsitcli/metadata.go:27 failed to find installations error="Epic is not installed in /home/msrd0g/.local/share/Steam/steamapps/common/Among Us"
[...]
2024-10-22T15:20:33+02:00 INF ficsitcli/metadata.go:27 failed to find installations error="Epic is not installed in /tmp"
2024-10-22T15:20:33+02:00 INF ficsitcli/metadata.go:27 failed to find installations error="failed to run lutris -lj: exec: \"flatpak\": executable file not found in $PATH"
2024-10-22T15:20:33+02:00 INF ficsitcli/metadata.go:27 failed to find installations error="Heroic not installed"
2024-10-22T15:20:33+02:00 INF ficsitcli/metadata.go:27 failed to find installations error="steam-flatpak not installed"
2024-10-22T15:20:33+02:00 INF ficsitcli/metadata.go:27 failed to find installations error="steam-snap not installed"
2024-10-22T15:20:33+02:00 INF disk/main.go:58 using local disk path=/home/msrd0g/HDD/SteamLibrary/steamapps/common/Satisfactory
2024-10-22T15:20:33+02:00 INF cli/installations.go:102 saving installations path=/home/msrd0g/.local/share/ficsit/installations.json
2024-10-22T15:20:33+02:00 INF cli/installations.go:102 saving installations path=/home/msrd0g/.local/share/ficsit/installations.json
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
Could not determine the accessibility bus address
panic: runtime error: index out of range [0] with length 0

goroutine 63 [running]:
github.com/satisfactorymodding/SatisfactoryModManager/backend/utils.GetDisplayBounds()
	/home/runner/work/SatisfactoryModManager/SatisfactoryModManager/backend/utils/display.go:22 +0x205
github.com/satisfactorymodding/SatisfactoryModManager/backend/app.(*app).ensureWindowVisible(0xc00047cfb0?)
	/home/runner/work/SatisfactoryModManager/SatisfactoryModManager/backend/app/window.go:41 +0x8c
github.com/satisfactorymodding/SatisfactoryModManager/backend/app.(*app).WatchWindow.func1()
	/home/runner/work/SatisfactoryModManager/SatisfactoryModManager/backend/app/window.go:24 +0x30
created by github.com/satisfactorymodding/SatisfactoryModManager/backend/app.(*app).WatchWindow in goroutine 16
	/home/runner/work/SatisfactoryModManager/SatisfactoryModManager/backend/app/window.go:18 +0xa7
```

These are the files that were created in `~/.local/share/ficsit`:

```
[msrd0g@msrd0-tower ~]$ bat .local/share/ficsit/installations.json
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .local/share/ficsit/installations.json
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {
   2   │   "selected_installation": "/home/msrd0g/HDD/SteamLibrary/steamapps/common/Satisfactory",
   3   │   "installations": [
   4   │     {
   5   │       "path": "/home/msrd0g/HDD/SteamLibrary/steamapps/common/Satisfactory",
   6   │       "profile": "Default",
   7   │       "vanilla": false
   8   │     }
   9   │   ],
  10   │   "version": 0
  11   │ }
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[msrd0g@msrd0-tower ~]$ bat .local/share/ficsit/profiles.json
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .local/share/ficsit/profiles.json
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {
   2   │   "profiles": {
   3   │     "Default": {
   4   │       "mods": null,
   5   │       "name": "Default",
   6   │       "required_targets": null
   7   │     }
   8   │   },
   9   │   "selected_profile": "",
  10   │   "version": 0
  11   │ }
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

I am running sway (wlroots/Wayland) on ArchLinux with steam running on a 2nd account that has access to my XWayland and Pulse/PipeWire servers.

### PR DESCRIPTION
**Pull request by msrd0**
Fixes #258 

I have no idea why no displays are detected and whether this is the correct fix or just a workaround. But it works for me and I don't know anything about Go so this is about the best fix I can provide.

### CODE REVIEW

**Comment by mircearoata** [comment]
Does this not result in the window constantly recentering itself, as it isn't overlapping the (0,0,0,0) range?

**Comment by msrd0** [comment]
@mircearoata I wouldn't know because windows don't get to choose their position and/or size. That's what tiling window managers do.

**Comment by mircearoata** [comment]
Oh, I missed that bit in your issue. I couldn't reproduce this issue, but since getting the displays uses XGB (go equivalent of XCB), I'm guessing that in your particular setup XGB somehow fails to connect to XWayland.

Please fix the lint issues and then I can merge this.

**Comment by msrd0** [comment]
> I'm guessing that in your particular setup XGB somehow fails to connect to XWayland.

Well, xrandr correctly identifies the screens, so I _think_ it should work.

> Please fix the lint issues and then I can merge this.

CI says

```
Error: File is not `gci`-ed with --skip-generated -s standard -s default -s prefix(github.com/satisfactorymodding/SatisfactoryModManager) -s blank -s dot --custom-order (gci)
```

I have absolutely 0 idea what that means and what you want me to do.

**Comment by mircearoata** [comment]
Run `golangci-lint run --fix`. But if you don't have golangci-lint installed, the issue is the indentation. It should be 2 tabs, but it's one tab and 3 spaces

**Comment by msrd0** [comment]
Yeah I don't have any editor with go integration, and emacs defaults to indent up to the first space when it doesn't know the language. I fixed the indentation.

**Pull request merged**
